version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: cart_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cart_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data: