
services:
  db:
    image: mysql:8.0
    container_name: cart_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cart_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      LANG: es_ES.UTF-8
      LC_ALL: es_ES.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cart_network

  app:
    image: cart-app
    container_name: cart_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cart_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - cart_network

volumes:
  db_data:

networks:
  cart_network: